BigQuery: adding missing dependency proto-google-cloud-bigquerystorage-v1beta1 to address NoClassDefFoundError com/google/cloud/bigquery/storage/v1beta1/Storage$CreateReadSessionRequest initiated by SourceService.checkConnection