BigQuery OpenCensus dependency (#2108)
* - reverting json-smart exclusions as it might be risky (current com.nimbusds:nimbus-jose-jwt version specifies hard bounds [1.3.1,2.3] and the explicit dependency entry 2.4.8 is not in that range)
- BigQuery: explicitly adding com.google.api:gax because of NoClassDefFoundError initiated by SourceService.checkConnection

* BigQuery: OpenCensus dependency to address NoClassDefFoundError initiated by SourceService.checkConnection

* BigQuery: Proper OpenCensus dependency referenced for io/opencensus/contrib/http/util/HttpPropagationUtil class