BigQuery missing dependencies (#2111)
* - reverting json-smart exclusions as it might be risky (current com.nimbusds:nimbus-jose-jwt version specifies hard bounds [1.3.1,2.3] and the explicit dependency entry 2.4.8 is not in that range)
- BigQuery: explicitly adding com.google.api:gax because of NoClassDefFoundError initiated by SourceService.checkConnection

* BigQuery: OpenCensus dependency to address NoClassDefFoundError initiated by SourceService.checkConnection

* BigQuery: Proper OpenCensus dependency referenced for io/opencensus/contrib/http/util/HttpPropagationUtil class

* BigQuery: Missing dependency gax-rpc added to address NoClassDefFoundError for com/google/api/gax/grpc/InstantiatingGrpcChannelProvider class initiated by CDMResultsAnalysisRunner.getObservationPeriodResults

* BigQuery: gax-grpc dependency typo fixed

* BigQuery: adding missing dependency proto-google-cloud-bigquerystorage-v1beta1 to address NoClassDefFoundError com/google/cloud/bigquery/storage/v1beta1/Storage$CreateReadSessionRequest initiated by SourceService.checkConnection