added library to pom-file (#1653)
* google jdbc driver version was changed to 1.28.0 (#1649)

* google jdbc driver version was changed to 1.2.11 (#1652)

* [BigQuery] NoClassDefFoundError: com/google/cloud/bigquery/storage/v1beta1/BigQueryStorageSettings #1652 - removed google-cloud-bigquery downgrade

* [BigQuery] NoClassDefFoundError: com/google/cloud/bigquery/storage/v1beta1/BigQueryStorageSettings #1652 - removed google-cloud-bigquery downgrade

Co-authored-by: Sergey Suvorov <sergey.suvorov@odysseusinc.com>
Co-authored-by: anton.abushkevich <anton.abushkevich>