- reverting json-smart exclusions as it might be risky (current com.nimbusds:nimbus-jose-jwt version specifies hard bounds [1.3.1,2.3] and the explicit dependency entry 2.4.8 is not in that range) (#2107)
- BigQuery: explicitly adding com.google.api:gax because of NoClassDefFoundError initiated by SourceService.checkConnection